theme = "sonokai"

[editor]
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.lsp]
display-messages = true
# display-inlay-hints = true


[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.insert]
j = {k = "normal_mode"}

[keys.normal.g]
q = ":reflow"

[keys.normal.space]
q = ":quit"
w = ":write"
